const allPeople:{id:number,full_Name:string,city:string,country:string,college:string ,vid:boolean }[]=[{id:1,full_Name:"Chucho Barke",city:"Leeds",country:"UK",college:"University of Liverpool",vid:false},
{id:2,full_Name:"Gil Bason",city:"El Paso",country:"United States",college:"Harvard University",vid:false},
{id:31,full_Name:"Pranjal Kumar",city:"Lucknow",country:"India",college:"Lucknow University",vid:true},
{id:3,full_Name:"Shanie Welden",city:"Bay Roberts",country:"Canada",college:"University of Toronto",vid:false},
{id:4,full_Name:"Lavena Silmon",city:"Stuttgart",country:"Germany",college:"University of Munich",vid:false},
{id:5,full_Name:"Dacey Woodstock",city:"Bordeaux",country:"France",college:"Université de Paris",vid:false},
{id:6,full_Name:"Gabriel Slimings",city:"London",country:"UK",college:"Imperial College",vid:true},
{id:7,full_Name:"Mady Coundley",city:"Paris",country:"France",college:"Sorbonne University",vid:false},
{id:8,full_Name:"Ros Sweetenham",city:"Evansville",country:"United States",college:"Georgia Tech",vid:false},
{id:9,full_Name:"Ettore Kuschel",city:"London",country:"UK",college:"King's College London",vid:false},
{id:10,full_Name:"Nevsa Dodsley",city:"Dallas",country:"United States",college:"Texas University",vid:false},
{id:11,full_Name:"Donal MacDiarmond",city:"London",country:"UK",college:"Boston University",vid:false},
{id:12,full_Name:"Cissy Kunkel",city:"Berlin",country:"Germany",college:"MIT",vid:true},
{id:13,full_Name:"Elwira Rossin",city:"Hamburg",country:"Germany",college:"University of Freiburg",vid:false},
{id:14,full_Name:"Joyann Mapletoft",city:"Monroe",country:"United States",college:"MIT",vid:false},
{id:15,full_Name:"Mordy Morillas",city:"Riyadh",country:"Saudi Arabia",college:"Riyadh University",vid:false},
{id:16,full_Name:"Cele Igglesden",city:"Najrān",country:"Saudi Arabia",college:"Najrān University",vid:false},
{id:17,full_Name:"Sandye Weinberg",city:"Montrouge",country:"France",college:"Yale University",vid:true},
{id:18,full_Name:"Brandais Dhillon",city:"Calgary",country:"Canada",college:"Calgary University",vid:false},
{id:19,full_Name:"Caprice Prosh",city:"Baltimore",country:"United States",college:"Prineton University",vid:false},
{id:20,full_Name:"Darda Malzard",city:"Montpellier",country:"France",college:"Cornell University",vid:false},
{id:21,full_Name:"Boyce Brangan",city:"Dubai",country:"United Arab Emirates",college:"Emirates University",vid:false},
{id:22,full_Name:"Amalia Seston",city:"Norfolk",country:"United States",college:"Yale University",vid:true},
{id:23,full_Name:"Rajan Singh",city:"New Delhi",country:"India",college:"IIT Kanpur",vid:false},
{id:24,full_Name:"Amie Jarrold",city:"Milwaukee",country:"United States",college:"Stanford University",vid:false}]

export default allPeople